### ISSUE TITLE
Nomenclature page is suppressed or empty

### ISSUE THREAD

**Issue by TLawanson** [ho-tex/pagesel#1]
I am trying to select a range of pages from my LaTeX document (on Overleaf) for output using pagesel. 
However, the nomenclature page is empty (in other cases suppressed) in the output. 

Here's a minimal working example: 

```
\documentclass[12pt, letterpaper, twoside]{article}
\usepackage[utf8]{inputenc}
\usepackage{lipsum}
\usepackage{nomencl}
\usepackage{amssymb}
\usepackage[5]{pagesel}

\makenomenclature

\title{First document}
\author{Hubert Farnsworth \thanks{funded by the Overleaf team}}
\date{February 2014}

\begin{document}

\begin{titlepage}
\maketitle
\end{titlepage}

\tableofcontents
\newpage

\section{Chapter 1}
\lipsum[2]

\newpage
\section{Chapter 2}
\lipsum[1]

\newpage
\section{Nomenclature}
\renewcommand{\nomname}{}
\nomenclature{\(c\)}{Speed of light in a vacuum}
\nomenclature{\(h\)}{Planck constant}
\nomenclature{\(+a\)}{Operator}
\nomenclature{\(2a\)}{Number}
\nomenclature{\(:a\)}{Punctuation symbol}
\nomenclature{\(Aa\)}{Uppercase letter}
\nomenclature{\(aa\)}{Lowercase letter}
\nomenclature{\(\alpha\)}{Greek character}
\printnomenclature

\end{document}

```
Expected output
<img width="192" alt="without_pagesel" src="https://user-images.githubusercontent.com/19898744/131708617-c9fcaa30-39bf-4f15-9583-da83edeb3f4d.PNG">

Output with pagesel
<img width="186" alt="with_pagesel" src="https://user-images.githubusercontent.com/19898744/131708621-9d550277-08a5-4718-84d4-6e44bff0832a.PNG">

**Comment by u-fischer** [comment]
pagesel sets `\nofiles`. That means if active not auxiliary files are written (this avoids that e.g. the labels in the aux-files are wrong).

So normally you should compile the document fully (include the needed makeindex call) without pagesel and then only activate it.

**Comment by TLawanson** [comment]
Thanks @u-fischer. I included the \makeindex call and compiled the document as you suggested (first without pagesel and then with pagesel). But the nomenclature still does not show up in Overleaf. Is there something I'm missing? 
Please see updated code below.

```
\documentclass[12pt, letterpaper, twoside]{article}
\usepackage[utf8]{inputenc}
\usepackage{lipsum}
\usepackage{nomencl}
\usepackage{amssymb}
\usepackage{imakeidx}
\makeindex
\usepackage[4-5]{pagesel}

\makenomenclature

\title{First document}
\author{Hubert Farnsworth \thanks{funded by the Overleaf team}}
\date{February 2014}

\begin{document}

\begin{titlepage}
\maketitle
\end{titlepage}

\tableofcontents
\newpage

\section{Chapter 1}
\lipsum[2]

\newpage
\section{Chapter 2}
\lipsum[1]

\newpage
\section{Nomenclature}
\renewcommand{\nomname}{}
\nomenclature{\(c\)}{Speed of light in a vacuum}
\nomenclature{\(h\)}{Planck constant}
\nomenclature{\(+a\)}{Operator}
\nomenclature{\(2a\)}{Number}
\nomenclature{\(:a\)}{Punctuation symbol}
\nomenclature{\(Aa\)}{Uppercase letter}
\nomenclature{\(aa\)}{Lowercase letter}
\nomenclature{\(\alpha\)}{Greek character}
\printnomenclature

\end{document}

```

**Comment by u-fischer** [comment]
overleaf probably removes the temporary files between the runs.  Ask the overleaf support for help. Locally it works for me.

**Comment by TLawanson** [comment]
Thanks @u-fischer. 
I was able to resolve the issue by including the nonofiles option for the pagesel package (found this in the pagesel documentation). 

`\usepackage[nonofiles, 4-5]{pagesel}`

Here's the updated code:
```
\documentclass[12pt, letterpaper, twoside]{article}
\usepackage[utf8]{inputenc}
\usepackage{lipsum}
\usepackage{nomencl}
\usepackage{amssymb}
\usepackage[nonofiles, 4-5]{pagesel}

\makenomenclature

\title{First document}
\author{Hubert Farnsworth \thanks{funded by the Overleaf team}}
\date{February 2014}

\begin{document}

\begin{titlepage}
\maketitle
\end{titlepage}

\tableofcontents
\newpage

\section{Chapter 1}
\lipsum[2]

\newpage
\section{Chapter 2}
\lipsum[1]

\newpage
\section{Nomenclature}
\renewcommand{\nomname}{}
\nomenclature{\(c\)}{Speed of light in a vacuum}
\nomenclature{\(h\)}{Planck constant}
\nomenclature{\(+a\)}{Operator}
\nomenclature{\(2a\)}{Number}
\nomenclature{\(:a\)}{Punctuation symbol}
\nomenclature{\(Aa\)}{Uppercase letter}
\nomenclature{\(aa\)}{Lowercase letter}
\nomenclature{\(\alpha\)}{Greek character}
\printnomenclature

\end{document}
```

**Comment by u-fischer** [comment]
sure this option exists, but be aware that this will also recreate aux-file and other temporary files, so references can be different.
In any case it is not an issue so I will close this.
